// Generated by '@poto/auto-import'
import blockPluginsTemplate from 'block-plugins-template'
import widget3 from './block-plugins/widget-3/index'
import widgetTest from './block-plugins/widget-test/index'
import widget1 from './block-plugins/widget1/index'

export const blockPlugins = {
  blockPluginsTemplate: { blockView: blockPluginsTemplate.blockView, blockSettingsView: blockPluginsTemplate.blockSettingsView, defaultSettings: blockPluginsTemplate.defaultSettings },
  widget1: { blockView: widget1.blockView, blockSettingsView: widget1.blockSettingsView, defaultSettings: widget1.defaultSettings },
  widget3: { blockView: widget3.blockView, blockSettingsView: widget3.blockSettingsView, defaultSettings: widget3.defaultSettings },
  widgetTest: { blockView: widgetTest.blockView, blockSettingsView: widgetTest.blockSettingsView, defaultSettings: widgetTest.defaultSettings },
}
