// Generated by '@poto/auto-import'
import type { BlockInfo } from '@poto/types'
import potoBlockPluginsTemplate from '@poto/block-plugins-template'
import widget3 from './block-plugins/widget-3/index'
import widgetTest from './block-plugins/widget-test/index'
import widget1 from './block-plugins/widget1/index'

export const BlockPlugins: BlockInfo = {
  potoBlockPluginsTemplate: { blockView: potoBlockPluginsTemplate.blockView, settingsView: potoBlockPluginsTemplate.settingsView, config: potoBlockPluginsTemplate.config },
  widget1: { blockView: widget1.blockView, settingsView: widget1.settingsView, config: widget1.config },
  widget3: { blockView: widget3.blockView, settingsView: widget3.settingsView, config: widget3.config },
  widgetTest: { blockView: widgetTest.blockView, settingsView: widgetTest.settingsView, config: widgetTest.config },
}
