// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BasicSetting: typeof import('./components/Settings/BasicSetting.vue')['default']
    BlockHandler: typeof import('./components/Widgets/BlockHandler.vue')['default']
    ColorSetting: typeof import('./components/Settings/ColorSetting.vue')['default']
    DiagramView: typeof import('./components/Widgets/Editor/views/DiagramView.vue')['default']
    Divider: typeof import('./components/Widgets/Divider.vue')['default']
    DividerSetting: typeof import('./components/Settings/DividerSetting.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElOptionGroup: typeof import('element-plus/es')['ElOptionGroup']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    FloatMenu: typeof import('./components/Widgets/FloatMenu.vue')['default']
    FontPicker: typeof import('./components/Widgets/FontPicker.vue')['default']
    Group: typeof import('./components/Widgets/Group.vue')['default']
    GroupSetting: typeof import('./components/Settings/GroupSetting.vue')['default']
    KatexView: typeof import('./components/Widgets/Editor/views/KatexView.vue')['default']
    LayoutWrapper: typeof import('./components/Widgets/LayoutWrapper.vue')['default']
    List: typeof import('./components/Widgets/List.vue')['default']
    Markdown: typeof import('./components/Widgets/Markdown.vue')['default']
    Milkdown: typeof import('./components/Widgets/Editor/Milkdown/Milkdown.vue')['default']
    PhotoSetting: typeof import('./components/Settings/PhotoSetting.vue')['default']
    PImage: typeof import('./components/Widgets/PImage.vue')['default']
    PImageSetting: typeof import('./components/Settings/PImageSetting.vue')['default']
    PText: typeof import('./components/Widgets/PText.vue')['default']
    PTextSetting: typeof import('./components/Settings/PTextSetting.vue')['default']
    Resizer: typeof import('./components/Widgets/Resizer.vue')['default']
    RingSetting: typeof import('./components/Settings/RingSetting.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TipTap: typeof import('./components/Widgets/Editor/TipTap.vue')['default']
    Wrapper: typeof import('./components/Widgets/Wrapper.vue')['default']
  }
}
