// Generated by '@poto/auto-import'
import type { BlockInfo } from '@poto/types'
import { blockInfo as potoBlockPluginsTemplate } from '@poto/block-plugins-template'
import { blockInfo as potoSoccerFormations } from '@poto/soccer-formations'

export const BlockPlugins: BlockInfo = {
  potoBlockPluginsTemplate,
  potoSoccerFormations,
}
