// Generated by '@poto/auto-import'
import type { BlockInfo } from '@poto/types'
import potoBlockPluginsTemplate from '@poto/block-plugins-template'

export const BlockPlugins: BlockInfo = {
  potoBlockPluginsTemplate: { blockView: potoBlockPluginsTemplate.blockView, settingsView: potoBlockPluginsTemplate.settingsView, config: potoBlockPluginsTemplate.config },
}
