// Generated by '@poto/auto-import'
import widgetPluginsTemplate from 'widget-plugins-template'
import widget3 from './widget-plugins/widget-3/index'
import widgetTest from './widget-plugins/widget-test/index'
import widget1 from './widget-plugins/widget1/index'

export const widgetPlugins = {
  widget1: { widgetView: widget1.widgetView, widgetSettingsView: widget1.widgetSettingsView, defaultSettings: widget1.defaultSettings },
  widget3: { widgetView: widget3.widgetView, widgetSettingsView: widget3.widgetSettingsView, defaultSettings: widget3.defaultSettings },
  widgetPluginsTemplate: { widgetView: widgetPluginsTemplate.widgetView, widgetSettingsView: widgetPluginsTemplate.widgetSettingsView, defaultSettings: widgetPluginsTemplate.defaultSettings },
  widgetTest: { widgetView: widgetTest.widgetView, widgetSettingsView: widgetTest.widgetSettingsView, defaultSettings: widgetTest.defaultSettings },
}
